### ISSUE TITLE
Tips: Should I continue to use svg-loader with vue-inline-svg?

### ISSUE THREAD

**Issue by bolducke** [shrpne/vue-inline-svg#11]
Hey,

I was asking myself. I start using svg-loader with Vue-cli, but it miss some key feature like dynamic rendering(as you do in this package). Are you aware of benefits to use svg-loader if I'm using your package?

Very nice work btw. This package should receive more attention than vue-simple-svg.

**Comment by shrpne** [comment]
Thank you!

I think you should choose what approach you prefer.
Svg-loader inlines svg into markup. No dynamic requests are needed but markup size grows. 
Vue-inline-svg works opposite. Markup stays clean. But you have to wait for images to load.

So maybe you can combine them in the way, that some images can be inlined and some can be loaded asynchronously.

**Comment by Tragio** [comment]
Just want to left here a reminder. You can always preload the .svg that you need so you can download them faster.
