### ISSUE TITLE
Attributes property generates as [object Object]

### ISSUE THREAD

**Issue by dangrima90** [shrpne/vue-inline-svg#16]
Hi I'm testing out this component, basically I'm trying to use the attributes property.

  ```
<inline-svg
    :src="svgPath"
    :width="width"
    :height="height"
    :fill="fill"
    :attributes="[{name: 'opacity', value: 0.25}]"
  >
  </inline-svg>
```

When the component is rendered the attributes don't seem to be attached to the svg. In fact when inspecting the element I see the following:

![image](https://user-images.githubusercontent.com/36479149/81796199-6338c600-950d-11ea-9b12-88914590fe98.png)

I expected to see `opacity="0.25"` as an attribute on the svg element. Is this an issue, or am I passing the wrong value to the attributes property?

**Comment by shrpne** [comment]
Hi! You should set SVG attributes like you set `fill` in your example.
Eg. `<inline-svg opacity="0.25" :stroke-opacity="myStrokeOpacity"/>`

`attributes` is not a component's prop that's why you get such strange output.
I will update readme to make it clearer.

**Comment by dangrima90** [comment]
Ah understood! Thanks for the clarification! Tested out and it worked :)
