### ISSUE TITLE
Change default svg storage location/path?

### ISSUE THREAD

**Issue by btrsco** [shrpne/vue-inline-svg#17]
Sorry if this doesn't have to do with your component. Still new to Vue, but when I use Laravel Mix the svgs are being copied from my `resources/svg/` folder to `public/images/` folder. I was wondering if there is anyway of changing this location to a separate location in the `public` folder to keep things organized as I usually do.

I've tried changing the `publicPath` option but no luck. I also tried moving all my svgs to the `public/assets/img/` folder with no luck either, just places them in `public/images/` still.

Again sorry if this isn't something you support or isn't an issue with vue-inline-svg.

**Comment by shrpne** [comment]
Indeed, vue-inline-svg doesn't affect how laravel-mix process images. I guess you should consult laravel-mix docs. Maybe this section could help https://laravel.com/docs/7.x/mix#url-processing

**Comment by btrsco** [comment]
Awesome, thank you for pointing me in the right way. Seems like this is an issue with Laravel Mix and their default webpack rules, unfortunately it's not possible to set a custom path for these images.

Thanks again!
