### ISSUE TITLE
Explain behaviour when an uncached svg is rendered multiple times as once

### ISSUE THREAD

**Issue by econic** [shrpne/vue-inline-svg#2]
The readme lacks documentation about the behaviour in the following case:

A currently uncached svg is rendered n times (could be hundreds of times in a typical list view).
How should the component handle network request(s)?
What is the current behaviour and what should the component do ideally?

I need this clarified to write a PR for https://github.com/shrpne/vue-inline-svg/issues/1 and probably other users would like to know before using this component.

I would recommend the following behaviour:
- the first component that renders realizes the svg is not cached and makes a request
- while the request is running, other components realize the svg is not cached but being fetched and register for the fetched event
- when fetched, all components get notified and render the svg

**Comment by shrpne** [comment]
Actually, it works as you describe :)

There is `cache` object that collects download promises, so if `cache[src]` exists — we know that image is fetching or already fetched and all we need is just handle fulfilled promise.

There is a line of text in the docs: "Loaded SVGs are cached so it will not make network request twice". I thought that the main point for users is that there is no duplication of network requests. And it is described in the docs. Do you think docs should be more detailed about internal implementation?
