### ISSUE TITLE
Some .svg files not showing properly

### ISSUE THREAD

**Issue by saint777** [shrpne/vue-inline-svg#22]
Hello @shrpne some .svg files not loading properly, e.g. this svg only shows arrow, with `<img src>` it works ok (shadows, backgrounds, borders etc)

Expected: https://i.imgur.com/26X33mD.png
Got this: https://i.imgur.com/AKgdKZS.png

plugin version: 2.0.0

looks like filters doesn't apply properly

`<svg width="96" height="96" viewBox="0 0 96 96" fill="none" xmlns="http://www.w3.org/2000/svg">
<g filter="url(#filter0_d)">
<rect x="15" y="6" width="66" height="66" rx="2" fill="white"/>
<rect x="15.5" y="6.5" width="65" height="65" rx="1.5" stroke="#848484"/>
</g>
<path fill-rule="evenodd" clip-rule="evenodd" d="M48 37.512L37.9693 48L34 44.6383L48 30L62 44.6383L58.0307 48L48 37.512Z" fill="#2F3B45"/>
<defs>
<filter id="filter0_d" x="0" y="0" width="96" height="96" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/>
<feOffset dy="9"/>
<feGaussianBlur stdDeviation="7.5"/>
<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.15 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape"/>
</filter>
</defs>
</svg>
`

**Comment by shrpne** [comment]
It works fine for me
https://codesandbox.io/s/fragrant-currying-jn4lh?file=/src/App.vue

What browser do you use?

**Comment by saint777** [comment]
> It works fine for me
> https://codesandbox.io/s/fragrant-currying-jn4lh?file=/src/App.vue
> 
> What browser do you use?

i'm using Chrome 85

and i'm actually using Nuxt.js
i had to use require
`InlineSvg(:src="require('~/assets/img/landing/scroll-to-top.svg')")` -> no errors but incorrect svg render

without require
`InlineSvg(src="~/assets/img/landing/scroll-to-top.svg")` -> vue-inline-svg.js?6d5e:178 GET http://localhost:3040/~/assets/img/landing/scroll-to-top.svg 404 (Not Found)

**Comment by saint777** [comment]
i found problem

i had several svgs with same filter ID's

**Comment by shrpne** [comment]
We have similar issue about unique ids #21, so I close it as duplicate for now
