### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by DenisaHalmaghi** [shrpne/vue-inline-svg#24]
For people using vue3 with typescript, in order to successfully import the module , they have to create a file ending with .d.ts in which they have the following piece of code:

```typescript
declare module 'vue-inline-svg'
```

**Comment by replygirl** [comment]
Is that so? I’m using `vite` and haven’t had to

**Comment by shrpne** [comment]
Some time types should be added.
Types conversation goes to #28
