### ISSUE TITLE
All SVG files with high priority

### ISSUE THREAD

**Issue by Tragio** [shrpne/vue-inline-svg#25]
Hello @shrpne! 🙂 

Thank you very much for your amazing work.

I've migrated from vue-svg-loader to vue-inline-svg, however, I noticed that all SVG are with a high priority (importance of high on the browser) and most of my SVG are on the footer. This is causing a big load of SVG loads that are not visible instead of loading the slider images that are at the start of the page.

I would love to know if you have any idea how to lazyload the SVGs using your plugin or any other technique. In my case, I'm using Gridsome.

Thank you very much and keep the good work.

**Comment by shrpne** [comment]
Hi! Thank you!

I guess you can make some wrapper component which will check if svg is in view

```  
<inline-svg src="my.svg" v-if="isInView"/>
```

You can use intersectionObserver to check if an element is in view, e.g. [vue-intersect](https://github.com/heavyy/vue-intersect)

**Comment by Tragio** [comment]
@shrpne thank you very much. Keep your good work 😃
