### ISSUE TITLE
Warning in Vue 3

### ISSUE THREAD

**Issue by daniesg** [shrpne/vue-inline-svg#26]
It looks like Vue 3 will issue warnings when a custom event is emitted , but it's not defined in the `emits` option.
https://v3.vuejs.org/guide/migration/emits-option.html#overview

Right now, I'm getting this warning in my console: *Component emitted event "loaded" but it is neither declared in the emits option nor as an "onLoaded" prop.*

I believe the solution is to just declare custom events in the `emits` option. I can open a pull request for this if that sounds good.

**Comment by shrpne** [comment]
Thank you!

> I believe the solution is to just declare custom events in the emits option.

I think it should be enough. PRs are welcome :)

**Comment by shrpne** [comment]
Fixed

Thank you for your help!
