### ISSUE TITLE
Vue 3 - Devtools will show component as Anonymous Component

### ISSUE THREAD

**Issue by MatthijsBe** [shrpne/vue-inline-svg#29]
Inside Vue 3 devtool, the inline SVG component will show up as: Anonymous Component
To fix this a name should be provided:  https://v3.vuejs.org/api/options-misc.html#name

**Comment by shrpne** [comment]
Is it new behavior in Vue 3? Looks like there is no such problem in Vue 2.

**Comment by MatthijsBe** [comment]
> Is it new behavior in Vue 3? Looks like there is no such problem in Vue 2.

As far I know yes, you need to provide a component name with vue 3

**Comment by syntag** [comment]
I've tried both ways on Vue 3, importing it as a component globally and on the Vue page itself.  Doesn't work as a plugin either. Here are the errors and warnings I get:

![](https://i.imgur.com/RG3rbDR.png)

**Comment by shrpne** [comment]
@SYNTAG looks like you are using a version of vue-inline-svg intended for vue2.
Vue3 version can be installed as `vue-inline-svg@next`

It is covered by dedicated docs section https://github.com/shrpne/vue-inline-svg#vue-v3

**Comment by syntag** [comment]
That worked, thank you for pointing that out. My apologies, I totally missed that in the docs.

**Comment by shrpne** [comment]
Fixed in 8a158a2b20c16021a897446a64cd1fd849709cf4
