### ISSUE TITLE
Disable inline svg optimization

### ISSUE THREAD

**Issue by n4ks** [shrpne/vue-inline-svg#34]
Hey! I am using complex SVG which I get from Adobe Illustrator. I optimize these SVGs very carefully as they contain certain inline styles that I cannot get rid of. It would be great if your library had an option (props?) That allows you not to optimize svg and connect them in the form in which they are in the project.

Unfortunately, the styles of these SVGs break if I connect them through your library, I experienced similar problems with some options when optimizing through SVGO.

This also applies to identifiers, after optimization, the identifiers that I use for animation turn into letters (A, B, etc)

**Comment by shrpne** [comment]
Hi! vue-inline-svg doesn't do any optimizations and keeps SVG content as is.

Can you provide a test case with your issue?

**Comment by n4ks** [comment]
Sorry, I think it was my mistake. They were displayed incorrectly due to an identifier conflict.
