### ISSUE TITLE
Set width and height of svg inside svg 

### ISSUE THREAD

**Issue by web-programmer-here** [shrpne/vue-inline-svg#36]
The svg I am trying to show has another svg inside it

```
<svg>
<defs ...></defs>
<g xmlns="http://www.w3.org/2000/svg">
   <svg xmlns="http://www.w3.org/2000/svg" ....></path></svg>  // how to add width and height to this?
</g>
</svg>
```

I cant seem to overwrite the width and height of this inner svg?

**Comment by web-programmer-here** [comment]
also tried this

```
const transform = (svg) => {
	svg.setAttributeNS(null, "width", "100px");
        svg.setAttributeNS(null, "height", "100px");
	return svg;
};
```

but it did not work

**Comment by shrpne** [comment]
> also tried this
> but it did not work


You should use `transformSource`, but in your code you are setting width to the root svg, you should query inner svg first
