### ISSUE TITLE
Does it support nuxtjs3?

### ISSUE THREAD

**Issue by todaynogada** [shrpne/vue-inline-svg#39]
Does it support nuxtjs3?
import InlineSvg from 'vue-inline-svg';

export default defineComponent({
    components: {
        InlineSvg,
    },

 <inline-svg src="~media/icons/duotune/text/txt001.svg" />

html output

help.

**Comment by shrpne** [comment]
Did you installed it as described in the dedicated section?
https://github.com/shrpne/vue-inline-svg#vue-v3

**Comment by todaynogada** [comment]
There was a problem with the path. I solved it. thank you.
