### ISSUE TITLE
How to install in Quasar - Need help

### ISSUE THREAD

**Issue by pravinfullstack** [shrpne/vue-inline-svg#40]
Thanks for this plugin.

I am looking for a solution to install in Quasar framework, any help would be appreciated.

**Comment by shrpne** [comment]
Quasar is just a plugin for Vue, so vue-inline-svg should work fine alongside it. I believe the installation guide in the readme should cover it

**Comment by pravinfullstack** [comment]
I tried creating a boot file after installing the package. And I don't see it working. 
Could you please create a simple demo ?

**Comment by pravinfullstack** [comment]
Got it working. while I installed it globally in boot file. I was using it incorrectly in my component.
I am using it now as 
```<inline-svg :src="require('@assets/img/signin.svg')" />```
