### ISSUE TITLE
Animation of SVG not working

### ISSUE THREAD

**Issue by L2k13** [shrpne/vue-inline-svg#43]
hey,

I'm using a svg generated with svgator. The animation is in a script tag in the SVG, but the animation doesn't start.

When I put the animation in a function and call it with the @loaded prop everything works fine.

So the SVG seems fine and so does the animation.

Now I'm looking for a solution how to start the animation directly from the SVG, since the SVG is maintained in a CMS and thus I can't manually insert the animation function into the vue component and its @loaded function

Does it only work with CSS animations or does anyone have an idea?

What I have already tried is:
- read the script tag with innerhtml and write it into the body via append child = no animation
- read script tag with innerhtml and trigger the read function in the @loaded with function / eval = error with unexpected token '&'

**Comment by shrpne** [comment]
Hi! VueInlinseSvg pastes svg content with `innerHTML`, looks like browser doesn't execute such scripts. You can use this workaround https://stackoverflow.com/a/20584396/4936667
