### ISSUE TITLE
TypeScript types are missing exports

### ISSUE THREAD

**Issue by pedrolamas** [shrpne/vue-inline-svg#44]
Currently, only the defaul type is exported, but the `InlineSvgComponent` and `InlineSvgPlugin` are not, so we get an error while trying to import on typescript files!

![image](https://user-images.githubusercontent.com/85504/196416383-14d0fba7-72f1-4100-a921-98290691c61d.png)

**Comment by shrpne** [comment]
Thank you for reaching out! I'm not very experienced with Typescript, are you willing to fix it with PR?

**Comment by pedrolamas** [comment]
Sure, I'll send a PR later today! 🙂
