### ISSUE TITLE
How to import for vue 3?

### ISSUE THREAD

**Issue by Glarionov** [shrpne/vue-inline-svg#55]
If I'm using 

```
import Notifications from '@kyvg/vue3-notification'
```

I'm getting error

**The requested module '/node_modules/.vite/deps/vue-inline-svg.js?v=3651ac09' does not provide an export named 'InlineSvgPlugin'**

If I'm using 

```
import Notifications from '@kyvg/vue3-notification@next'
```

I'm getting error
**Failed to resolve import "vue-inline-svg@next" from "resources\js\app.js"**

**Comment by shrpne** [comment]
You should consult with @kyvg/vue3-notification author, i have no relation with it
