### ISSUE TITLE
First SVG loaded on all inline-svg tags

### ISSUE THREAD

**Issue by develm** [shrpne/vue-inline-svg#6]
Each <inline-svg> tag loads same svg file (first one loaded in page) irrelevant of src attribute.

**Comment by shrpne** [comment]
I can't reproduce it, can you provide a minimal test case, please?

**Comment by develm** [comment]
Issue was caused by improperly exported svg icons, once we exported icons properly the problem went away.

**Comment by kravchenkoWeb** [comment]
@develm can you please provide more details about how icons should be exported? 
I faced same issue when added `<inline-svg />` inside of `v-for` where icon path is different for each item.
