### ISSUE TITLE
syntax when svg path comes from vue tag

### ISSUE THREAD

**Issue by kaspar-allenbach** [shrpne/vue-inline-svg#63]
I want to use this in a loop and print the path from the router, but I can't get it to work.
What would be the right syntax here?

This works:

```
<template v-for="value in $router.options.routes">
  <RouterLink :to="{ name: value.name, params: { city: currentCity } }">
    <img :src="value.iconPath" alt=""> // this is a svg
     {{ value.name }}
  </RouterLink>
</template>
```

Something like: 

```<inline-svg :src="require(`${value.iconPath}`)"/>```

I can't get the syntax right. Can you help me?

**Comment by shrpne** [comment]
It depends on a bundler you use, for example, here are Vite docs https://vitejs.dev/guide/assets

The simplest solution is to put icons into [public](https://vitejs.dev/guide/assets#the-public-directory) directory, so paths will be kept as is
