### ISSUE TITLE
Fix declaration emit

### ISSUE THREAD

**Issue by Salmon42** [shrpne/vue-inline-svg#64]
Hello, I encountered the following problem:

In a Vue 3 SFC (Options API), I am importing and using the `InlineSvg` component:

![image](https://github.com/user-attachments/assets/fb73c4e9-8c19-49ce-90bf-adc95259748f)

![image](https://github.com/user-attachments/assets/30ec6c1a-c878-4ef8-9950-7f279dedb283)

I am encountering the following error (bound to the first line of `<script>` SFC part):

![image](https://github.com/user-attachments/assets/5415c639-ce11-4f10-ae2d-89dd89f705af)

---

After digging a bit around, I found out that the problem is in `.d.ts` file not explicitly exporting the component props separately. This is quite weird in my opinion, because I expect the export of `_default` in https://github.com/shrpne/vue-inline-svg/blob/master/types/index.d.ts would work correctly either way. Unfortunately, this is not true in my case.

What fixes the issue for me is to explicitly export the `InlineSvg` interface in the `index.d.ts` file:

```ts
export interface InlineSvg {
    src: string;
    title?: string;
    transformSource?: (svg: SVGElement) => SVGElement;
    keepDuringLoading?: boolean;
}
```

Using:
* Vue 3.5.4
* Vite 5.2.8
* TypeScript 5.4.0

Could you add the exporting there? Or can I somehow do the update and query a PR?
Thanks~

**Comment by shrpne** [comment]
Hello! Thank you for detailed info.

Added "export interface" in v3.1.4
