### ISSUE TITLE
Failing with "Cannot read property 'attributes' of undefined"

### ISSUE THREAD

**Issue by colinbes** [shrpne/vue-inline-svg#7]
Using:
- @vue/cli 3.11.0
- vue 2.6.10
- vue-inline-svg 1.1.2

Registered locally in component as shown in README

And used in HelloWorld template as `<inline-svg src="../assets/heart.svg"> </inline-svg>`

On running I get error in console stating
```
Uncaught (in promise) TypeError: Cannot read property 'attributes' of undefined
    at eval (index.js?e54a:81)
```

Snippet showing error (using chrome inspector)
```
cache[src].then((svg) => {
                // copy attrs
                this.svgAttrs = {};
                const attrs = svg.attributes;
                for (let i = attrs.length - 1; i >= 0; i--) {
                    this.svgAttrs[attrs[i].name] = attrs[i].value;
                }
```

This is a totally clean vue-cli project created for this test and is available at https://github.com/colinbes/inlinesvgtest

inline-svg added in HelloWorld component https://github.com/colinbes/inlinesvgtest/blob/master/src/components/HelloWorld.vue

**Comment by shrpne** [comment]
Thank you for the test case.
Here is a problem, that vue-cli doesn't automatically handle such asset in component's prop, as it does for `<img>`
So InlineSvg tries to load '/assets/heart.svg', but there is no such file and it fallbacks to index.html page, InlineSvg tries to parse index.html as SVG, but there is no SVG inside so it fails with error.

You need to make a hint to file-loader, that heart.svg should be processed as an asset:
```
<inline-svg :src="require('../assets/heart.svg')"/>
```
Or move heart.svg to the `public` directory so it will be available to download by direct link

You can learn more about assets handling with vue-cli
https://cli.vuejs.org/guide/html-and-static-assets.html#static-assets-handling

But you are right that InlineSvg should not fail to load corrupted file, instead, it should emit `error` event, I have fixed it in https://github.com/shrpne/vue-inline-svg/releases/tag/v1.1.3

**Comment by colinbes** [comment]
Thanks so much, not only does that solve the problem, but I get to learn more. 

Would you mind finishing sentence "...such asset in component's prop, as it does for" as I suspect it could help a lot of us.

I am happy to fork project and do a PR but it may be simpler just to add comment to README about providing the hint for files not in public folder. I was trying using require("") and not having luck but didn't think of binding src (silly me).

Thanks again.

**Comment by shrpne** [comment]
I have updated previous comment, `<img>` was invisible without quotes.

Also I have added a note to the readme about vue-loader.

BTW you can edit other's readme directly on github, it will make fork and PR automatically :)

**Comment by colinbes** [comment]
> BTW you can edit other's readme directly on github, it will make fork and PR automatically :)
That's awesome, thanks!
